name: BioJS
description: Represent all biological data on the web
url: http://biojs.net
markdown: kramdown
pygments: false
timezone: UTC
encoding: utf-8
cats:
    - name: demo
      desc: Demonstration of components
    - name: 101_tutorial
      desc: "101 Tutorial series"
      numbering: true
    - name: tutorials
      desc: Basic tutorials
    - name: howto
      desc: How-Tos about components
