name: BioJS
description: Represent all biological data on the web
url: http://biojs.net
markdown: kramdown
pygments: false
timezone: UTC
encoding: utf-8
cats:
    - name: demo
      desc: Demonstration
    - name: tutorials
      desc: Tutorials and Stuff
    - name: howto
      desc: How-Tos
