name: BioJS
description: Represent all biological data on the web
url: http://biojs.net
markdown: kramdown
#pygments: false
#highlighter: pygments
timezone: UTC
encoding: utf-8
cats:
    demo:
      desc: Demonstration of components
    101_tutorial:
      desc: "101 Tutorial series"
      numbering: true
    tutorials:
      desc: Basic tutorials
    howto:
      desc: How-Tos about components
