name: BioJS
description: Represent all biological data on the web
url: http://biojs.net
markdown: kramdown
#pygments: false
#highlighter: pygments
timezone: UTC
encoding: utf-8
exclude: [vendor]
cats:
    demo:
      desc: Demonstration of components
    101_tutorial:
      desc: "101 Tutorial series"
      numbering: true
    102_tutorial:
      desc: "102 Tutorial series (Advanced)"
      numbering: true
    howto:
      desc: How-Tos about components
    playground:
      desc: BioJS playground
